# Generated by Django 3.1.7 on 2021-08-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_childtable_childid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childtable',
            name='childid',
            field=models.IntegerField(blank=True, default=0, max_length=5),
        ),
    ]
