# Generated by Django 3.1.7 on 2021-08-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_auto_20210820_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childtable',
            name='childid',
        ),
    ]
