# Generated by Django 3.1.7 on 2021-08-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_remove_childtable_childid'),
    ]

    operations = [
        migrations.AddField(
            model_name='childtable',
            name='childid',
            field=models.CharField(default=50, max_length=10),
            preserve_default=False,
        ),
    ]
