# Generated by Django 3.1.7 on 2021-08-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0007_auto_20210820_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childtable',
            old_name='childid',
            new_name='childcode',
        ),
    ]
