# Generated by Django 3.1.7 on 2021-08-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0008_auto_20210820_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='childtable',
            name='blood',
            field=models.CharField(default=35, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childtable',
            name='childage',
            field=models.CharField(default=40, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childtable',
            name='childheight',
            field=models.CharField(default=50, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childtable',
            name='childweight',
            field=models.CharField(default=50, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childtable',
            name='gender',
            field=models.CharField(default=50, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childtable',
            name='health',
            field=models.CharField(default=50, max_length=10),
            preserve_default=False,
        ),
    ]
