# Generated by Django 3.1.7 on 2021-07-26 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgencyTable',
        ),
    ]
